MedBook.Collections = {
  Samples: Samples,
  SampleGroups: SampleGroups,
  Contrasts: Contrasts,
  GeneExpression: GeneExpression,
  IsoformExpression: IsoformExpression,
  GeneAnnotation: GeneAnnotation,
  Signatures: Signatures,
  SignatureScores: SignatureScores,
  Genes: Genes,
  Jobs: Jobs,
  Blobs: Blobs,
  Expression2: Expression2,
  Networks: Networks,
  NetworkElements: NetworkElements,
  NetworkInteractions: NetworkInteractions,
  Studies: Studies,
  Patients: Patients,
  CohortSignatures: CohortSignatures,
  Mutations: Mutations,
};
